/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-11-23 18:56:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainScreen_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("        <title>SaiKiran BookStores</title>\r\n");
      out.write("        <!-- Default Stylesheets -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/slider.css\"  />\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/slider.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("    // This is the script for the banner slider\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $('#slider').s3Slider({\r\n");
      out.write("            timeOut: 7000\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/myScript.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("        ");

        if (session.getAttribute("user") == null ){// THen new user, show join now
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

        }else {
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

        }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id = \"banner\">\r\n");
      out.write("        <div class=\"container_16\">\r\n");
      out.write("            <div class=\"grid_16\" style=\"padding-left: 20px; \" id=\"slider\">\t\r\n");
      out.write("                <ul id=\"sliderContent\">\t\t\r\n");
      out.write("                    <!-- Duplicate this code for each image -->\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"sliderImage\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                        <img src=\"images/banner/b1.png\" width=\"900\" height=\"300\" /> \r\n");
      out.write("\r\n");
      out.write("                        <span class=\"top\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                            <strong>Fountain Pens...</strong>\t\r\n");
      out.write("\r\n");
      out.write("                            <br>From the International and Indian markets, we have the variety of the High Class fountain \r\n");
      out.write("\r\n");
      out.write("                            pens. Available now for you to get your hands on.\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </li>  \r\n");
      out.write("                    <li class=\"sliderImage\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                        <img src=\"images/banner/b2.png\" width=\"900\" height=\"300\" /> \r\n");
      out.write("\r\n");
      out.write("                        <span class=\"top\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                            <strong>Books, Diaries...</strong>\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("                            <br>Text Books, Single Lines, Double Lines, Red 'n Blue Lines, Fullscape Books\r\n");
      out.write("\r\n");
      out.write("                            Drawing Books, and all the paper you want to write all throughout to learn \r\n");
      out.write("\r\n");
      out.write("                            Available now at your doorsteps* \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </li>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"sliderImage\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                        <img src=\"images/banner/b5.png\" width=\"900\" height=\"300\" /> \r\n");
      out.write("\r\n");
      out.write("                        <span class=\"top\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                            <strong>Kids Colors...</strong>\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("                            <br>Collection of Non-Toxic childrens colors available\r\n");
      out.write("\r\n");
      out.write("                            Let your child learn the art of painting at an early age \r\n");
      out.write("\r\n");
      out.write("                            by having his hands on the colors available here... \r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </li>  \r\n");
      out.write("\r\n");
      out.write("                    <li class=\"sliderImage\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                        <img src=\"images/banner/b7.jpg\" width=\"900\" height=\"300\" /> \r\n");
      out.write("\r\n");
      out.write("                        <span class=\"top\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                            <strong>Graphic Novels...</strong>\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("                            <br>The most amazing titles that you always wanted to get your hands onn.. \r\n");
      out.write("\r\n");
      out.write("                            Now you have the opportunity to have them all in your personal library.\r\n");
      out.write("\r\n");
      out.write("                            International as well as Indian titles of many authors available\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </li>   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"sliderImage\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                        <img src=\"images/banner/b6.png\" width=\"900\" height=\"300\" /> \r\n");
      out.write("\r\n");
      out.write("                        <span class=\"top\" style=\"display: none; \">\r\n");
      out.write("\r\n");
      out.write("                            <strong>Color World...</strong>\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("                            <br>A vast variety of different sets of colors including Oil-Pastels,\r\n");
      out.write("\r\n");
      out.write("                            Pencil Colors, Poster Colors, Acrylic Colors and many more...\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </li>   \r\n");
      out.write("\r\n");
      out.write("                    <div class=\"clear sliderImage\"></div>  \r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container_16\">\r\n");
      out.write("        <div id = \"contents\">\r\n");
      out.write("            <!-- LeftSide -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div id=\"leftside\" class=\"grid_3\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <ul id=\"leftsideNav\">\r\n");
      out.write("                        <li><a href=\"#\"><strong>Categories</strong></a></li>\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"adv\">\r\n");
      out.write("                    <h2><br/>This is The Header of an Advertisement</h2>\r\n");
      out.write("                    <p>We offer Advertisement display here </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Middle -->\r\n");
      out.write("        <div id=\"middle\"class=\"grid_13\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--The Middle Content Div Closing -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--The Center Content Div Closing -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
